name: RunicTabList
version: '${version}'
main: com.runicrealms.runictablist.RunicTabList
api-version: 1.19
depend:
  - ProtocolLib
  - RunicCommon
  - RunicDatabase
  - RunicCore
  - RunicGuilds
  - LuckPerms
